events {
    # Definição de quantas conexões simultâneas cada processo do Nginx pode gerenciar
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Configurações básicas de otimização e ocultação de versão

    # Ativa uma otimização crucial do Kernel do Linux. Em vez de copiar dados do disco para a memória do Nginx
    # e depois para a rede, o Nginx envia o arquivo do disco direto para o canal de rede. Economiza CPU e memória drasticamente.
    sendfile            on;

    # Faz o Nginx enviar cabeçalhos HTTP e o corpo do arquivo em um único pacote TCP completo, otimizando a largura de banda.
    tcp_nopush          on;

    # Evita que pequenos pacotes de dados fiquem esperando na fila para acumular tamanho (desativa o algoritmo de Nagle).
    # Essencial para APIs REST, pois faz com que as respostas JSON viajem o mais rápido possível.
    tcp_nodelay         on;

    # Mantém a conexão TCP com o cliente aberta por 65 segundos. Se o mesmo usuário fizer outra requisição logo em seguida
    # (como o seu Bot Bun disparando chamadas seguidas), ele reutiliza a mesma conexão física em vez de gastar tempo criando uma nova.
    keepalive_timeout   65;

    # Segurança básica. Remove a versão do Nginx das respostas de erro (ex: esconde o "Nginx/1.25.3"). Isso impede que atacantes
    # descubram vulnerabilidades específicas da sua versão do proxy.
    server_tokens       off;

    limit_req_zone $binary_remote_addr zone=limite_por_ip:10m rate=5r/s;
    limit_req_zone $http_x_telegram_id zone=limite_por_usuario:10m rate=10r/s;

    server {
        listen 80;
        server_name localhost;

        location / {
            if ($http_x_telegram_id = "") {
                add_header Content-Type application/json;
                return 403 '{"timestamp": "$time_iso8601", "status": 403, "error": "Forbidden", "message": "Acesso negado. Cabeçalho X-Telegram-Id ausente."}';
            }

            # Rate Limits
            limit_req zone=limite_por_ip burst=5 nodelay;
            limit_req zone=limite_por_usuario burst=2 nodelay;

            # Proxy Configs
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass http://api:8080;

            proxy_connect_timeout 5s;
            proxy_read_timeout    60s;
        }

        error_page 503 @rate_limited;
        location @rate_limited {
            default_type application/json;
            return 429 '{"timestamp": "$time_iso8601", "status": 429, "error": "Too Many Requests", "message": "Muitas requisições. Por favor, aguarde um momento."}';
        }
    }
}